jobs:
  # login-to-azure:
  #   executor: azure-cli/azure-docker
  #   steps:
  #     - azure-cli/login-with-service-principal
  #     - run:
  #         command: az resource list
  #         name: List resources of tenant stored as `AZURE_SP_TENANT` env var
  deploy:
    working_directory: ~/repo
    executor: node/default
    steps:
      - checkout
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - run:
          command: az resource list
          name: List resources of tenant stored as `AZURE_SP_TENANT` env var
      # docker:
      #   - image: circleci/node:10.16.3
      # steps:

      - run:
          name: Install Azure functions tools
          command: sudo npm i -g azure-functions-core-tools@3 --unsafe-perm true
      - run:
          name: Deploy to Azure function App
          command: func azure functionapp publish $FUNCTION_APP_NAME --javascript

orbs:
  azure-cli: circleci/azure-cli@1.0.0
  node: circleci/node@4.1.0
version: 2.1
workflows:
  login-workflow:
    jobs:
      - deploy
